In [1]:
from jupiter import Moons
moons_data = Moons()
moons_data.data

,period_days,distance_km,radius_km,mag,mass_kg,group,ecc,inclination_deg
moon,,,,,,,,
Adrastea,0.298000,129000.0,8.20,NaN,NaN,Inner,0.001500,0.03
Aitne,730.000000,23231000.0,1.50,22.70,NaN,Carme,0.264000,165.00
Amalthea,0.498000,181400.0,83.50,14.10,2.080000e+18,Inner,0.003190,0.37
Ananke,630.000000,21300000.0,14.00,18.90,NaN,Ananke,0.174725,148.60
Aoede,761.000000,24000000.0,2.00,22.50,NaN,Pasiphae,0.432000,158.00
Arche,724.000000,22931000.0,1.50,22.80,NaN,Carme,0.259000,165.00
Autonoe,719.000000,23039000.0,2.00,22.00,NaN,Pasiphae,0.334000,153.00
Callirrhoe,787.000000,24583090.0,4.80,20.80,NaN,Pasiphae,0.309570,148.00
Callisto,16.689018,1882700.0,2410.30,5.65,1.075938e+23,Galilean,0.007400,2.02
Carme,693.000000,22579850.0,23.35,18.90,NaN,Carme,0.229493,163.00
Carpo,456.000000,16989000.0,1.50,23.00,NaN,other,0.430000,51.40
Chaldene,760.000000,24006280.0,2.00,22.50,NaN,Carme,0.150086,164.00
Cyllene,738.000000,24349000.0,1.00,23.20,NaN,Pasiphae,0.319000,149.00
Dia,287.000000,12118000.0,2.00,22.40,NaN,Himalia,0.211000,28.30
Eirene,744.000000,23731770.0,2.00,22.50,NaN,Carme,0.241300,162.70
Elara,259.000000,11703130.0,40.00,16.60,NaN,Himalia,0.196149,30.50
Erinome,683.000000,22354200.0,1.50,22.80,NaN,Carme,0.205256,164.80
Ersa,252.000000,11483000.0,1.50,22.90,NaN,Himalia,0.094000,30.61
Euanthe,603.000000,20799000.0,1.50,22.80,NaN,Ananke,0.232000,148.90
Eukelade,693.000000,23661000.0,2.00,22.60,NaN,Carme,0.272000,165.50
Eupheme,628.000000,21199710.0,1.00,23.40,NaN,Ananke,0.253000,148.00
Euporie,551.000000,19302000.0,1.00,23.10,NaN,Ananke,0.144000,145.80
Europa,3.551181,670900.0,1560.80,5.29,4.799844e+22,Galilean,0.009000,1.79
Eurydome,723.000000,23214490.0,1.50,22.70,NaN,Pasiphae,0.297537,150.00
Ganymede,7.150000,1070400.0,2634.10,4.61,1.481900e+23,Galilean,0.001300,2.20
Harpalyke,624.000000,21280180.0,2.00,22.20,NaN,Ananke,0.160268,148.29
Hegemone,740.000000,23947000.0,1.50,22.80,NaN,Pasiphae,0.328000,155.20
Helike,635.000000,21263000.0,2.00,22.60,NaN,Ananke,0.156000,154.80
Hermippe,607.000000,20665870.0,2.00,22.10,NaN,Ananke,0.198252,146.70
Herse,715.000000,23097000.0,1.00,23.40,NaN,Carme,0.200000,164.20
Himalia,248.000000,11388690.0,85.00,14.60,4.200000e+18,Himalia,0.153786,29.90
Io,1.750000,421700.0,1821.60,5.02,8.931938e+22,Galilean,0.004100,2.20
Iocaste,641.000000,21431650.0,2.50,21.80,NaN,Ananke,0.329491,149.40
Isonoe,689.000000,23322670.0,2.00,22.50,NaN,Carme,0.226312,164.40
Kale,737.000000,23512340.0,1.00,23.00,NaN,Carme,0.289346,166.20
Kallichore,765.000000,24043000.0,1.00,23.70,NaN,Carme,0.264000,165.50
Kalyke,767.000000,24147770.0,3.50,21.80,NaN,Carme,0.302822,165.90
Kore,779.000000,24543000.0,1.00,23.60,NaN,Pasiphae,0.325000,145.00
Leda,242.000000,11195980.0,10.75,20.20,NaN,Himalia,0.164879,27.60
Lysithea,258.000000,11700710.0,21.00,18.20,NaN,Hamilia,0.147873,26.30
Megaclite,747.000000,23736190.0,3.00,21.70,NaN,Pasiphae,0.410217,143.00
Metis,0.290000,128000.0,21.50,NaN,NaN,Inner,0.000200,2.00
Mneme,620.000000,21069000.0,1.00,23.30,NaN,Ananke,0.227000,148.60
Orthosie,629.000000,21170540.0,1.00,23.10,NaN,Ananke,0.483724,148.00
Pandia,252.000000,11525000.0,1.50,23.00,NaN,Himalia,0.180000,28.00
Pasiphae,722.000000,23208940.0,28.90,16.90,NaN,Pasiphae,0.611016,153.00
Pasithee,711.000000,22967990.0,1.00,23.20,NaN,Carme,0.209703,165.00
Philophrosyne,701.000000,22819950.0,1.00,23.50,NaN,Pasiphae,0.194000,144.00
Praxidike,609.000000,21147000.0,3.50,21.20,NaN,Ananke,0.230000,149.00
Sinope,777.000000,24371650.0,17.50,18.30,NaN,Pasiphae,0.336655,158.00
Sponde,735.000000,23487000.0,1.00,23.00,NaN,Pasiphae,0.312000,151.00
Taygete,692.000000,22546240.0,2.50,21.90,NaN,Carme,0.248754,166.00
Thebe,0.670000,221889.0,49.00,NaN,NaN,Inner,0.017500,1.10
Thelxinoe,628.000000,21162000.0,1.00,23.50,NaN,Ananke,0.221000,151.40
Themisto,130.000000,7396130.0,4.50,21.00,NaN,other,0.252211,45.30
Thyone,604.000000,20940000.0,2.00,22.30,NaN,Ananke,0.229000,148.50

In [12]:
moons_data.plot